package edu.mum.hrms.model;

// Generated 2015-6-25 10:57:41 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysCode generated by hbm2java
 */
@Entity
@Table(name = "sys_code_category")
public class SysCodeCategory implements java.io.Serializable {

	private long categoryId;
	
	private String categoryName;

	private Integer status;
	
	private Integer editable;
	
	public SysCodeCategory() {
	}

	public SysCodeCategory(long categoryId) {
		this.categoryId = categoryId;
	}

	@Id
	@Column(name = "CATEGORY_ID", unique = true)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CATEGORY_NAME")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "EDITABLE")	
	public Integer getEditable() {
		return editable;
	}

	public void setEditable(Integer editable) {
		this.editable = editable;
	}

}
