package edu.mum.hrms.model;

// Generated 2015-6-21 18:21:45 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role")
public class SysRole implements java.io.Serializable {

	private long roleId;

	private String localRoleName;

	private String enRoleName;

	private String description;

	private Integer seq;

	private Long createId;

	private Date createTime;

	private Long updateId;

	private Date updateTime;

	private Integer isSys;
	
	private Long deptId;
	
	private Integer status;
	
	
	/**
	 * @see edu.mum.hrms.util.AppConstants
	 */
	private String roleType;

//	private Set specialRoleVisacenterMaps = new HashSet(0);
//
//	private Set sysRoleUserMaps = new HashSet(0);

	public SysRole() {
	}

	public SysRole(long roleId) {
		this.roleId = roleId;
	}


	
	@Id
	@Column(name = "ROLE_ID", unique = true)
//	@SequenceGenerator(name = "SEQ_SYS_ROLE", sequenceName = "SEQ_SYS_ROLE",allocationSize = 1)
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_SYS_ROLE")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "LOCAL_ROLE_NAME", length = 100)
	public String getLocalRoleName() {
		return this.localRoleName;
	}

	public void setLocalRoleName(String localRoleName) {
		this.localRoleName = localRoleName;
	}

	@Column(name = "EN_ROLE_NAME", length = 100)
	public String getEnRoleName() {
		return this.enRoleName;
	}

	public void setEnRoleName(String enRoleName) {
		this.enRoleName = enRoleName;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SEQ", precision = 8, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "CREATE_ID", precision = 10, scale = 0)
	public Long getCreateId() {
		return this.createId;
	}

	public void setCreateId(Long createId) {
		this.createId = createId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 26)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATE_ID", precision = 10, scale = 0)
	public Long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Long updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 26)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "IS_SYS", precision = 1, scale = 0)
	public Integer getIsSys() {
		return this.isSys;
	}

	public void setIsSys(Integer isSys) {
		this.isSys = isSys;
	}
	
	@Column(name = "ROLE_TYPE")
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}
	
	@Column(name = "DEPT_ID", precision = 10, scale = 0)
	public Long getDeptId() {
		return deptId;
	}
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}
	@Column(name = "STATUS", precision = 1, scale = 0)
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	
	
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
//	public Set getSpecialRoleVisacenterMaps() {
//		return this.specialRoleVisacenterMaps;
//	}
//
//	public void setSpecialRoleVisacenterMaps(Set specialRoleVisacenterMaps) {
//		this.specialRoleVisacenterMaps = specialRoleVisacenterMaps;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
//	public Set getSysRoleUserMaps() {
//		return this.sysRoleUserMaps;
//	}
//
//	public void setSysRoleUserMaps(Set sysRoleUserMaps) {
//		this.sysRoleUserMaps = sysRoleUserMaps;
//	}

}
